export const RELOAD_AGENDADOS='RELOAD_AGENDADOS';
export const DONT_RELOAD='DONT_RELOAD_AGENDADOS';

export const RELOAD_PACIENTES='RELOAD_Pacientes';
export const DONT_RELOAD_PACIENTES='DONT_RELOAD_Pacientes';

export const RELOAD_EMPRESAS="RELOAD_EMPRESAS";
export const DONT_RELOAD_EMPRESAS='DONT_RELOAD_EMPRESAS'

export const RELOAD_INICIO='RELOAD_INICIO';
export const DONT_RELOAD_INICIO="DONT_RELOAD_INICIO"


export const BROADCAST="BROADCAST";
