POST http://localhost:8080/api/routes/tipo_estado/update.php
db_user: servidorLabmed
db_password: labmed2019

{
    "_id": 7,
    "nome": "TESTE",
    "descricao": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sed odio urna. Phasellus faucibus diam at dignissim sollicitudin. Nunc nisl neque, luctus vel erat in, pulvinar."
}