POST http://localhost:8080/api/routes/fatura/update.php
db_user: servidorLabmed
db_password: labmed2019

{
    "_id": 1,
    "status": 1,
    "descricao": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tempor a ex a "
}