POST  http://localhost:8080/api/routes/exame/new.php
db_user: servidorLabmed
db_password: labmed2019

{
    "nome": "MODELO",
    "descricao": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tempor a ex.",
    "preco": "00",
    "codigo": "00000000"
}